version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - gradle clean build

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'