version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 19
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build

cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - '**/*'