server:
  servlet:
    context-path: /advertise-system/v1
  port: 8081
management:
  endpoints:
    web:
      base-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_advertise?createDatabaseIfNotExist=true
    username: root
    password: root