server:
  servlet:
    context-path: /advertise-system/v1
  port: 8080
management:
  endpoints:
    web:
      base-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://advert-rds.cjdz8mocsswq.us-east-1.rds.amazonaws.com:3306/db_advertise?serverTimezone=UTC&useSSL=false